import { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { MessageCircle, Send, User as UserIcon, BookOpen, Clock, CheckCircle, Sparkles, Heart, Brain, Stethoscope, Bot, Zap, TrendingUp, Volume2, VolumeX } from 'lucide-react';
import { PrimaryButton } from '../ui/PrimaryButton';
import { Textarea } from '../ui/textarea';
import { Input } from '../ui/input';
import { GeminiService } from '../../services/GeminiService';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface Message {
  id: string;
  role: 'user' | 'bot';
  content: string;
  citation?: string;
  timestamp: string;
}

interface ProfessorQuery {
  id: string;
  subject: string;
  question: string;
  status: 'pending' | 'answered';
  timestamp: string;
  answer?: string;
  professor?: string;
}

export function AskPage() {
  const [activeTab, setActiveTab] = useState<'medibot' | 'professor'>('medibot');
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      role: 'bot',
      content: "Hello! I'm MediBot, your AI-powered medical learning assistant. I can help you understand complex medical concepts, clarify doubts, and provide instant answers. How can I assist you today?",
      timestamp: new Date().toLocaleTimeString(),
    },
  ]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Scroll to bottom on updates
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isTyping]);

  const quickSuggestions = [
    { icon: Heart, text: 'Explain cardiac cycle phases', color: '#EF476F', category: 'Cardiology' },
    { icon: Brain, text: 'Neurotransmitter types', color: '#00A896', category: 'Neuroscience' },
    { icon: Stethoscope, text: 'COPD vs Asthma differences', color: '#FFD166', category: 'Pulmonology' },
    { icon: Zap, text: 'Fluid and electrolyte balance', color: '#00A896', category: 'Physiology' },
    { icon: TrendingUp, text: 'Stages of wound healing', color: '#EF476F', category: 'Pathology' },
    { icon: Bot, text: 'Antibiotics mechanism of action', color: '#FFD166', category: 'Pharmacology' },
  ];

  const [professorQueries, setProfessorQueries] = useState<ProfessorQuery[]>([
    {
      id: '1',
      subject: 'Cardiovascular Physiology',
      question: 'Can you explain the Frank-Starling mechanism in detail?',
      status: 'answered',
      timestamp: '2 hours ago',
      answer: 'The Frank-Starling mechanism describes the relationship between stroke volume and end-diastolic volume...',
      professor: 'Dr. James Wilson',
    },
    {
      id: '2',
      subject: 'Pharmacology',
      question: 'What are the key differences between ACE inhibitors and ARBs?',
      status: 'pending',
      timestamp: '1 day ago',
    },
  ]);

  const [askProfessorForm, setAskProfessorForm] = useState({
    subject: '',
    question: '',
  });

  // Stop speech when the component unmounts (user changes page)
  useEffect(() => {
    return () => {
      GeminiService.stopSpeech();
    };
  }, []);

  const toggleMute = () => {
    setIsMuted((prev) => {
      const newState = !prev;
      if (newState) {
        GeminiService.stopSpeech();
      }
      return newState;
    });
  };

  const handleSend = async () => {
    if (!input.trim()) return;

    // Stop any existing speech immediately when user asks a new question
    GeminiService.stopSpeech();

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input,
      timestamp: new Date().toLocaleTimeString(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    try {
      const responseText = await GeminiService.generateResponse(input);

      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'bot',
        content: responseText,
        citation: 'Generated by Gemini AI',
        timestamp: new Date().toLocaleTimeString(),
      };

      setMessages((prev) => [...prev, botMessage]);

      // Speak the response (strip markdown for better speech) if not muted
      if (!isMuted) {
        const cleanText = responseText.replace(/[*#_`]/g, '');
        GeminiService.speakResponse(cleanText);
      }
    } catch (error) {
      console.error("Error generating response:", error);
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'bot',
        content: "Sorry, I'm having trouble connecting to my brain right now. Please try again later.",
        timestamp: new Date().toLocaleTimeString(),
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsTyping(false);
    }
  };

  const handleAskProfessor = () => {
    if (!askProfessorForm.subject || !askProfessorForm.question) return;

    const newQuery: ProfessorQuery = {
      id: Date.now().toString(),
      subject: askProfessorForm.subject,
      question: askProfessorForm.question,
      status: 'pending',
      timestamp: 'Just now',
    };

    setProfessorQueries((prev) => [newQuery, ...prev]);
    setAskProfessorForm({ subject: '', question: '' });
  };

  const handleSuggestionClick = async (text: string) => {
    // Stop any existing speech immediately
    GeminiService.stopSpeech();

    setInput(text);
    // Auto-send after a short delay
    setTimeout(async () => {
      setInput(text);
      const userMessage: Message = {
        id: Date.now().toString(),
        role: 'user',
        content: text,
        timestamp: new Date().toLocaleTimeString(),
      };
      setMessages((prev) => [...prev, userMessage]);
      setInput('');
      setIsTyping(true);

      try {
        const responseText = await GeminiService.generateResponse(text);

        const botMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'bot',
          content: responseText,
          citation: 'Generated by Gemini AI',
          timestamp: new Date().toLocaleTimeString(),
        };

        setMessages((prev) => [...prev, botMessage]);

        // Speak the response (strip markdown for better speech) if not muted
        if (!isMuted) {
          const cleanText = responseText.replace(/[*#_`]/g, '');
          GeminiService.speakResponse(cleanText);
        }
      } catch (error) {
        console.error("Error generating response:", error);
        const errorMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'bot',
          content: "Sorry, I'm having trouble connecting to my brain right now. Please try again later.",
          timestamp: new Date().toLocaleTimeString(),
        };
        setMessages((prev) => [...prev, errorMessage]);
      } finally {
        setIsTyping(false);
      }
    }, 100);
  };

  return (
    <div className="min-h-screen pt-20 pb-20 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">

          {/* Left Column: Dynamic Content (Chat or Professor) */}
          <div className="lg:col-span-3">
            <AnimatePresence mode="wait">
              {activeTab === 'medibot' ? (
                <motion.div
                  key="medibot"
                  initial={{ opacity: 0, x: -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  transition={{ duration: 0.3 }}
                  className="bg-card border-2 border-border rounded-3xl overflow-hidden flex flex-col shadow-xl"
                  style={{ height: '85vh' }}
                >
                  {/* Chat Header */}
                  <div className="p-6 border-b-2 border-border bg-gradient-to-r from-[#00A896]/10 to-[#028090]/10">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-4">
                        <motion.div
                          animate={{
                            boxShadow: [
                              '0 0 20px rgba(0, 168, 150, 0.3)',
                              '0 0 30px rgba(0, 168, 150, 0.5)',
                              '0 0 20px rgba(0, 168, 150, 0.3)',
                            ]
                          }}
                          transition={{ repeat: Infinity, duration: 2 }}
                          className="w-16 h-16 rounded-2xl bg-gradient-to-br from-[#00A896] to-[#028090] flex items-center justify-center"
                        >
                          <Bot size={32} className="text-white" />
                        </motion.div>
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <h2 className="text-xl font-semibold">MediBot Assistant</h2>
                            <button
                              onClick={toggleMute}
                              className="p-1.5 rounded-full hover:bg-black/10 transition-colors"
                              title={isMuted ? "Unmute Voice" : "Mute Voice"}
                            >
                              {isMuted ? <VolumeX className="w-4 h-4 text-muted-foreground" /> : <Volume2 className="w-4 h-4 text-[#00A896]" />}
                            </button>
                          </div>
                          <div className="text-sm text-muted-foreground flex items-center gap-2">
                            <motion.div
                              animate={{ scale: [1, 1.2, 1] }}
                              transition={{ repeat: Infinity, duration: 2 }}
                              className="w-2 h-2 rounded-full bg-green-500"
                            />
                            Online • AI-Powered Medical Expert
                          </div>
                        </div>
                      </div>
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ repeat: Infinity, duration: 10, ease: 'linear' }}
                        className="text-[#00A896]"
                      >
                        <Sparkles size={28} />
                      </motion.div>
                    </div>
                  </div>

                  {/* Messages */}
                  <div className="flex-1 overflow-y-auto p-6 space-y-6">
                    <AnimatePresence>
                      {messages.map((message) => (
                        <motion.div
                          key={message.id}
                          initial={{ opacity: 0, y: 10, scale: 0.95 }}
                          animate={{ opacity: 1, y: 0, scale: 1 }}
                          exit={{ opacity: 0, scale: 0.95 }}
                          transition={{ type: 'spring', damping: 20 }}
                          className={`flex gap-4 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}
                        >
                          <motion.div
                            whileHover={{ scale: 1.1, rotate: 5 }}
                            className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${message.role === 'bot'
                              ? 'bg-gradient-to-br from-[#00A896] to-[#028090]'
                              : 'bg-gradient-to-br from-[#FFD166] to-[#FFD166]/80'
                              }`}
                          >
                            {message.role === 'bot' ? (
                              <Bot size={24} className="text-white" />
                            ) : (
                              <UserIcon size={24} className="text-white" />
                            )}
                          </motion.div>
                          <div className={`flex-1 max-w-3xl ${message.role === 'user' ? 'text-right' : ''}`}>
                            <motion.div
                              whileHover={{ scale: 1.01, y: -2 }}
                              className={`inline-block p-5 rounded-2xl shadow-md ${message.role === 'user'
                                ? 'bg-gradient-to-br from-[#00A896] to-[#028090] text-white'
                                : 'bg-muted text-foreground'
                                }`}
                            >
                              {message.role === 'bot' ? (
                                <div className="prose prose-sm dark:prose-invert max-w-none text-left">
                                  <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {message.content}
                                  </ReactMarkdown>
                                </div>
                              ) : (
                                <div className="text-base leading-relaxed whitespace-pre-wrap">{message.content}</div>
                              )}
                            </motion.div>
                            <div className="mt-2 text-xs text-muted-foreground flex items-center gap-2">
                              <span>{message.timestamp}</span>
                              {message.citation && (
                                <>
                                  <span>•</span>
                                  <span>{message.citation}</span>
                                </>
                              )}
                            </div>
                          </div>
                        </motion.div>
                      ))}
                    </AnimatePresence>

                    {/* Typing Indicator */}
                    <AnimatePresence>
                      {isTyping && (
                        <motion.div
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          exit={{ opacity: 0, y: 10 }}
                          className="flex gap-4"
                        >
                          <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-[#00A896] to-[#028090] flex items-center justify-center">
                            <Bot size={24} className="text-white" />
                          </div>
                          <div className="bg-muted p-5 rounded-2xl">
                            <div className="flex gap-2">
                              {[0, 1, 2].map((i) => (
                                <motion.div
                                  key={i}
                                  animate={{
                                    y: [0, -10, 0],
                                    opacity: [0.5, 1, 0.5]
                                  }}
                                  transition={{
                                    repeat: Infinity,
                                    duration: 1,
                                    delay: i * 0.2
                                  }}
                                  className="w-2.5 h-2.5 rounded-full bg-[#00A896]"
                                />
                              ))}
                            </div>
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                    <div ref={messagesEndRef} />
                  </div>

                  {/* Input */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="p-6 border-t-2 border-border bg-gradient-to-br from-muted/30 to-background"
                  >
                    <div className="flex gap-3 mb-3">
                      <div className="flex-1 relative">
                        <motion.input
                          type="text"
                          value={input}
                          onChange={(e) => setInput(e.target.value)}
                          onKeyPress={(e) => e.key === 'Enter' && handleSend()}
                          placeholder="Ask me anything about medicine..."
                          whileFocus={{ scale: 1.01 }}
                          className="w-full px-6 py-4 rounded-2xl bg-background border-2 border-border focus:outline-none focus:border-[#00A896] transition-all shadow-sm text-base"
                        />
                        <AnimatePresence>
                          {input && (
                            <motion.div
                              initial={{ scale: 0, opacity: 0 }}
                              animate={{ scale: 1, opacity: 1 }}
                              exit={{ scale: 0, opacity: 0 }}
                              className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-muted-foreground bg-muted px-2 py-1 rounded"
                            >
                              Press Enter
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                      <motion.button
                        onClick={handleSend}
                        whileHover={{ scale: 1.05, rotate: 5 }}
                        whileTap={{ scale: 0.95 }}
                        className="px-8 py-4 bg-gradient-to-br from-[#00A896] to-[#028090] text-white rounded-2xl flex items-center gap-2 shadow-lg shadow-[#00A896]/30 disabled:opacity-50 disabled:cursor-not-allowed"
                        disabled={!input.trim()}
                      >
                        <Send size={20} />
                        <span className="hidden sm:inline">Send</span>
                      </motion.button>
                    </div>
                    <div className="flex items-center justify-center gap-2">
                      <motion.div
                        animate={{ scale: [1, 1.2, 1] }}
                        transition={{ repeat: Infinity, duration: 2 }}
                        className="w-2 h-2 rounded-full bg-green-500"
                      />
                      <p className="text-xs text-muted-foreground">
                        MediBot uses AI to provide educational responses. Always verify critical information.
                      </p>
                    </div>
                  </motion.div>
                </motion.div>
              ) : (
                <motion.div
                  key="professor"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  transition={{ duration: 0.3 }}
                  className="space-y-6"
                >
                  {/* Ask Professor Form */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="bg-card border-2 border-border rounded-2xl p-6 shadow-lg"
                  >
                    <h2 className="mb-4">Submit a Question to Professors</h2>
                    <div className="space-y-4">
                      <div>
                        <label className="text-sm mb-2 block">Subject/Topic</label>
                        <Input
                          placeholder="e.g., Cardiovascular System, Pharmacology"
                          value={askProfessorForm.subject}
                          onChange={(e) => setAskProfessorForm({ ...askProfessorForm, subject: e.target.value })}
                        />
                      </div>
                      <div>
                        <label className="text-sm mb-2 block">Your Question</label>
                        <Textarea
                          placeholder="Describe your question in detail. Include any relevant context..."
                          rows={5}
                          className="resize-none"
                          value={askProfessorForm.question}
                          onChange={(e) => setAskProfessorForm({ ...askProfessorForm, question: e.target.value })}
                        />
                      </div>
                      <motion.div
                        whileHover={{ scale: 1.01 }}
                        className="flex items-start gap-3 p-4 bg-muted rounded-xl"
                      >
                        <Clock size={20} className="text-[#FFD166] mt-1" />
                        <div className="text-sm">
                          <p className="mb-1">Expected Response Time: 12-24 hours</p>
                          <p className="text-muted-foreground text-xs">
                            Questions are reviewed by available professors. You'll receive a notification when answered.
                          </p>
                        </div>
                      </motion.div>
                      <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                        <PrimaryButton onClick={handleAskProfessor} className="w-full">
                          Submit Question
                        </PrimaryButton>
                      </motion.div>
                    </div>
                  </motion.div>

                  {/* Previous Queries */}
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                  >
                    <h2 className="mb-4">Your Questions</h2>
                    <div className="space-y-4">
                      {professorQueries.map((query, index) => (
                        <motion.div
                          key={query.id}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: index * 0.05 }}
                          whileHover={{ scale: 1.01, x: 5 }}
                          className="bg-card border-2 border-border rounded-2xl p-6 shadow-md hover:shadow-lg hover:border-[#00A896] transition-all"
                        >
                          <div className="flex items-start justify-between mb-3">
                            <div className="flex-1">
                              <div className="flex items-center gap-3 mb-2">
                                <h3 className="text-foreground">{query.subject}</h3>
                                <motion.span
                                  whileHover={{ scale: 1.1 }}
                                  className={`px-3 py-1 rounded-full text-xs ${query.status === 'answered'
                                    ? 'bg-green-500/20 text-green-500'
                                    : 'bg-[#FFD166]/20 text-[#FFD166]'
                                    }`}
                                >
                                  {query.status === 'answered' ? (
                                    <><CheckCircle className="inline mr-1" size={12} /> Answered</>
                                  ) : (
                                    <><Clock className="inline mr-1" size={12} /> Pending</>
                                  )}
                                </motion.span>
                              </div>
                              <p className="text-muted-foreground text-sm">{query.question}</p>
                            </div>
                          </div>

                          {query.answer && (
                            <motion.div
                              initial={{ opacity: 0, height: 0 }}
                              animate={{ opacity: 1, height: 'auto' }}
                              className="mt-4 p-4 bg-muted rounded-xl"
                            >
                              <div className="flex items-center gap-2 mb-2">
                                <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#00A896] to-[#028090] flex items-center justify-center text-white text-xs">
                                  {query.professor?.split(' ').map(n => n[0]).join('')}
                                </div>
                                <div>
                                  <p className="text-sm">{query.professor}</p>
                                  <p className="text-xs text-muted-foreground">{query.timestamp}</p>
                                </div>
                              </div>
                              <p className="text-sm text-foreground">{query.answer}</p>
                            </motion.div>
                          )}

                          {!query.answer && (
                            <p className="text-xs text-muted-foreground mt-2">
                              Submitted {query.timestamp}
                            </p>
                          )}
                        </motion.div>
                      ))}
                    </div>
                  </motion.div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Right Column: Sidebar */}
          <div className="space-y-4">
            {/* Tab Switcher */}
            <div className="bg-card border-2 border-border p-2 rounded-3xl shadow-lg flex flex-col gap-2">
              <motion.button
                onClick={() => setActiveTab('medibot')}
                whileHover={{ scale: 1.02, x: 5 }}
                whileTap={{ scale: 0.98 }}
                className={`w-full flex items-center gap-3 px-6 py-4 rounded-2xl transition-all relative overflow-hidden ${activeTab === 'medibot'
                  ? 'bg-gradient-to-br from-[#00A896] to-[#028090] text-white shadow-xl shadow-[#00A896]/30'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted'
                  }`}
              >
                {activeTab === 'medibot' && (
                  <motion.div
                    layoutId="tabBackground"
                    className="absolute inset-0 bg-gradient-to-br from-[#00A896] to-[#028090]"
                    transition={{ type: 'spring', damping: 25, stiffness: 300 }}
                  />
                )}
                <div className="relative z-10"><MessageCircle size={20} /></div>
                <span className="relative z-10 font-medium">MediBot AI</span>
              </motion.button>

              <motion.button
                onClick={() => setActiveTab('professor')}
                whileHover={{ scale: 1.02, x: 5 }}
                whileTap={{ scale: 0.98 }}
                className={`w-full flex items-center gap-3 px-6 py-4 rounded-2xl transition-all relative overflow-hidden ${activeTab === 'professor'
                  ? 'bg-gradient-to-br from-[#FFD166] to-[#FFD166]/80 text-white shadow-xl shadow-[#FFD166]/30'
                  : 'text-muted-foreground hover:text-foreground hover:bg-muted'
                  }`}
              >
                {activeTab === 'professor' && (
                  <motion.div
                    layoutId="tabBackground"
                    className="absolute inset-0 bg-gradient-to-br from-[#FFD166] to-[#FFD166]/80"
                    transition={{ type: 'spring', damping: 25, stiffness: 300 }}
                  />
                )}
                <div className="relative z-10"><BookOpen size={20} /></div>
                <span className="relative z-10 font-medium">Ask Professor</span>
              </motion.button>
            </div>

            {/* Quick Suggestions & Other Sidebar Content */}
            <AnimatePresence>
              {activeTab === 'medibot' && (
                <motion.div
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 20 }}
                  className="bg-card border-2 border-border rounded-2xl p-5 shadow-lg"
                >
                  <div className="flex items-center gap-2 mb-4">
                    <Sparkles size={18} className="text-[#FFD166]" />
                    <h3 className="text-sm">Quick Topics</h3>
                  </div>
                  <div className="grid grid-cols-2 gap-2">
                    {quickSuggestions.map((suggestion, index) => (
                      <motion.button
                        key={index}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={() => handleSuggestionClick(suggestion.text)}
                        className="p-3 bg-muted border border-border rounded-xl hover:border-[#00A896] transition-all text-left flex flex-col items-center justify-center text-center h-full"
                      >
                        <suggestion.icon size={20} style={{ color: suggestion.color }} className="mb-2" />
                        <span className="text-xs leading-tight">{suggestion.text}</span>
                      </motion.button>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

        </div>
      </div>
    </div>
  );
}
